name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: extract tag version
        id: next_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - run: echo ${GITHUB_REF}
      - run: echo ${{ steps.next_version.outputs.VERSION }}